#!/usr/bin/env bash
#
# Container startup for MalDet. Three jobs before handing off to the app:
#   1. materialise config.py from environment variables
#   2. wait for MySQL to actually accept connections
#   3. make sure ClamAV has a signature database
#
set -euo pipefail

say() { printf '[maldet] %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. config.py
#
# Every module does `from config import ...`, and config.py is gitignored
# because it holds credentials. Rather than rewrite that import across five
# files, generate the file here from the environment.
#
# The "only if absent" check matters: when the project directory is
# bind-mounted for live editing, the developer's real config.py is sitting
# right there, and clobbering it would destroy their local credentials.
# ---------------------------------------------------------------------------
if [ -f /app/config.py ]; then
    say "config.py already present — leaving it alone"
else
    say "generating config.py from environment variables"
    python3 - <<'PY'
import os

# repr() the values so quotes, backslashes and empty strings survive.
settings = {
    "GITHUB_TOKEN": os.environ.get("GITHUB_TOKEN", ""),
    "DB_HOST":      os.environ.get("DB_HOST", "db"),
    "DB_USER":      os.environ.get("DB_USER", "fypuser"),
    "DB_PASSWORD":  os.environ.get("DB_PASSWORD", ""),
    "DB_NAME":      os.environ.get("DB_NAME", "fyp_scanner"),
}

with open("/app/config.py", "w") as f:
    f.write("# Generated by docker/entrypoint.sh at container start.\n")
    f.write("# Edit the .env file and restart rather than editing this.\n\n")
    for key, value in settings.items():
        f.write(f"{key} = {value!r}\n")

if not settings["GITHUB_TOKEN"]:
    print("[maldet] WARNING: GITHUB_TOKEN is empty. Repo lookups will hit "
          "GitHub's unauthenticated rate limit (60/hour) and most scans "
          "will fail. Set it in .env and restart.")
PY
fi

# ---------------------------------------------------------------------------
# 2. Wait for MySQL
#
# compose already gates on the db healthcheck, but that reports when the
# server answers ping — not necessarily when this user/database is usable,
# and first boot also has to import the schema and seed data. So verify the
# connection this app will actually make.
# ---------------------------------------------------------------------------
say "waiting for the database"
python3 - <<'PY'
import sys, time
import pymysql
from config import DB_HOST, DB_USER, DB_PASSWORD, DB_NAME

DEADLINE_SECONDS = 180
last_error = None
start = time.monotonic()

while time.monotonic() - start < DEADLINE_SECONDS:
    try:
        conn = pymysql.connect(host=DB_HOST, user=DB_USER, password=DB_PASSWORD,
                                database=DB_NAME, connect_timeout=5)
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM repositories")
            (n,) = cur.fetchone()
        conn.close()
        print(f"[maldet] database ready — {n} repositories on record")
        sys.exit(0)
    except Exception as e:          # noqa: BLE001 — any failure means "not yet"
        last_error = e
        time.sleep(2)

sys.exit(f"[maldet] database never became usable within {DEADLINE_SECONDS}s. "
         f"Last error: {last_error}")
PY

# ---------------------------------------------------------------------------
# 3. ClamAV signature database
#
# clamscan is useless without signatures, and scanner.py's run_clamav()
# swallows the failure and returns no findings — so a missing database looks
# exactly like a clean scan. Fetch it up front instead, and say so loudly.
#
# /var/lib/clamav is a named volume, so this download happens once and
# survives restarts. Set SKIP_FRESHCLAM=1 to opt out.
# ---------------------------------------------------------------------------
if [ "${SKIP_FRESHCLAM:-0}" = "1" ]; then
    say "SKIP_FRESHCLAM=1 — skipping signature download (ClamAV will report nothing)"
elif compgen -G "/var/lib/clamav/*.c[vl]d" > /dev/null; then
    say "ClamAV signatures already present"
else
    say "downloading ClamAV signatures (~110MB, one time — cached in a volume)"
    # Non-fatal: every other engine still works without ClamAV, and per
    # NOTES.md it has yet to produce a single hit on this corpus.
    if freshclam --stdout --log=/var/log/clamav/freshclam.log; then
        say "ClamAV signatures ready"
    else
        say "WARNING: signature download failed — ClamAV will report nothing."
        say "         Every other engine is unaffected. Retry by restarting."
    fi
fi

say "starting: $*"
exec "$@"
